protected/models/Lowongan.php
<?php

/**
 * This is the model class for table "lowongan".
 *
 * The followings are the available columns in table 'lowongan':
 * @property integer $id_lowongan
 * @property string $tanggal
 * @property integer $bagian
 * @property integer $jabatan
 * @property integer $tipe
 * @property string $deskripsi_pekerjaan
 * @property string $deskripsi_kebutuhan
 * @property integer $jumlah_orang
 * @property string $tanggal_kebutuhan
 * @property string $lokasi
 * @property integer $status
 * @property string $jeniskelamin
 * @property integer $umur
 * @property integer $monitor
 * @property integer $jenjang
 * @property integer $nilai
 * @property integer $perusahaan_id
 * @property integer $user_id
 * @property integer $verifikasi_id
 * @property string $verifikasi_tanggal
 */
class Lowongan extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'lowongan';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('tanggal, bagian, jabatan, tipe, deskripsi_pekerjaan, deskripsi_kebutuhan, jumlah_orang, tanggal_kebutuhan, lokasi, status, jeniskelamin, umur, perusahaan_id, jenjang, nilai', 'required'),
			array('bagian, jabatan, tipe, jumlah_orang, status, umur, perusahaan_id, user_id, verifikasi_id', 'numerical', 'integerOnly'=>true),
            array('lokasi, tanggal_kebutuhan, verifikasi_tanggal', 'length', 'max'=>255),
            array('nilai', 'length', 'max'=>5),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
            array('id_lowongan, tanggal, bagian, jabatan, tipe, deskripsi_pekerjaan, deskripsi_kebutuhan, jumlah_orang, tanggal_kebutuhan, lokasi, status', 'safe', 'on'=>'search'),
            );
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'Bagian' => array(self::BELONGS_TO, 'Bagian', 'bagian'),
            'Jabatan' => array(self::BELONGS_TO, 'Jabatan', 'jabatan'),
            'Perusahaan' => array(self::BELONGS_TO, 'Perusahaan', 'perusahaan_id'),
            );
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id_lowongan' => 'Id Lowongan',
			'tanggal' => 'Tanggal Posting',
			'bagian' => 'Bagian',
			'jabatan' => 'Jabatan',
			'tipe' => 'Tipe',
			'deskripsi_pekerjaan' => 'Deskripsi Pekerjaan',
			'deskripsi_kebutuhan' => 'Keahlian Khusus',
			'jumlah_orang' => 'Jumlah Orang',
			'tanggal_kebutuhan' => 'Batas Waktu',
			'lokasi' => 'Lokasi Penempatan',
			'jeniskelamin' => 'Jenis Kelamin',
			'status' => 'Status',
            'umur' => 'Maksimal Umur',
            'jenjang' => 'Jenjang Pendidikan',
            'nilai' => 'Nilai / IPK Minimal',
            'perusahaan_id' => 'Perusahaan',
            'user_id' => 'Diposting Oleh',
            'verifikasi_id' => 'Diverifikasi Oleh',
            'verifikasi_tanggal' => 'Verifikasi Tanggal',
            );
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id_lowongan',$this->id_lowongan);
		$criteria->compare('tanggal',$this->tanggal,true);
		$criteria->compare('bagian',$this->bagian);
		$criteria->compare('jabatan',$this->jabatan);
		$criteria->compare('tipe',$this->tipe);
		$criteria->compare('deskripsi_pekerjaan',$this->deskripsi_pekerjaan,true);
		$criteria->compare('deskripsi_kebutuhan',$this->deskripsi_kebutuhan,true);
		$criteria->compare('jumlah_orang',$this->jumlah_orang);
		$criteria->compare('tanggal_kebutuhan',$this->tanggal_kebutuhan,true);
		$criteria->compare('lokasi',$this->lokasi,true);
		$criteria->compare('status',$this->status);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
			));
	}


    public function searchCompany($id)
    {
        // @todo Please modify the following code to remove attributes that should not be searched.

        $criteria=new CDbCriteria;

        $criteria->compare('id_lowongan',$this->id_lowongan);
        $criteria->compare('tanggal',$this->tanggal,true);
        $criteria->compare('bagian',$this->bagian);
        $criteria->compare('jabatan',$this->jabatan);
        $criteria->compare('tipe',$this->tipe);
        $criteria->compare('deskripsi_pekerjaan',$this->deskripsi_pekerjaan,true);
        $criteria->compare('deskripsi_kebutuhan',$this->deskripsi_kebutuhan,true);
        $criteria->compare('jumlah_orang',$this->jumlah_orang);
        $criteria->compare('tanggal_kebutuhan',$this->tanggal_kebutuhan,true);
        $criteria->compare('lokasi',$this->lokasi,true);
        $criteria->compare('status',$this->status);
        $criteria->condition = "user_id = :user_id";
        $criteria->params=(array(':user_id'=>$id));

        return new CActiveDataProvider($this, array(
            'criteria'=>$criteria,
            ));
    }    

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Lowongan the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	public function tipe($data){
		if($data==1){
			return "Karyawan Tetap";
		}else{
			return "Karyawan Kontak";
		}
	}

	public function status($data){
		if($data==1){
			return "Tersedia";
		}else{
			return "Ditutup";
		}
	}	

    public function statusLabel($data){
        if($data==1){
            return "label label-info";
        }else{
            return "label label-danger";
        }
    }       

    protected function beforeSave()
    {
      $this->tanggal = date('Y-m-d', strtotime($this->tanggal));
      $this->tanggal_kebutuhan = date('Y-m-d', strtotime($this->tanggal_kebutuhan));
      return TRUE;
  }
  
  protected function afterFind()
  {
      $this->tanggal = date('d-m-Y', strtotime($this->tanggal));
      return TRUE;
  }   

  public function frmDate($date,$code){
      $explode = explode("-",$date);
      $year  = $explode[0];
      (substr($explode[1],0,1)=="0")?$month=str_replace("0","",$explode[1]):$month=is_string($explode[1]);
      $dated = $explode[2];
      $explode_time = explode(" ",$dated);
      $dates = $explode_time[0];        

      switch($code){
                // Per Object
                case 4: $format = $dates; break;                                                            // 01
                case 5: $format = $month; break;                                                            // 01
                case 6: $format = $year; break;                                                                // 2011
            }        
            return $format;
        }    

        public function now($code=1){
        	switch($code){
        		case 1: $date = date("Y-m-d H:i:s"); break;
        		case 2: $date = date("Y-m-d"); break;
        		case 3: $date = date("H:i:s"); break;
        	}
        	return $date;
        }

        public function nmonth($month){
        	$thn_kabisat = date("Y") % 4;
        	($thn_kabisat==0)?$feb=29:$feb=28;
            $init_month = array(1=>31,    // Januari [current]
                                2=>$feb,    // Feb
                                3=>31,    // Mar
                                4=>30,    // Apr
                                5=>31,    // Mei
                                6=>30,    // Juni
                                7=>31,    // Juli
                                8=>31,    // Aug
                                9=>30,    // Sep
                                10=>31,    // Oct    
                                11=>30,    // Nov
                                12=>31);// Des
            $nmonth = $init_month[$month];
            return $nmonth;
        }

        public function dateRange($start,$end){
        	$xdate    =$this->frmDate($start,4);
        	$ydate    =$this->frmDate($end,4);
        	$xmonth   =$this->frmDate($start,5);
        	$ymonth   =$this->frmDate($end,5);
        	$xyear    =$this->frmDate($start,6);
        	$yyear    =$this->frmDate($end,6);
        	if($xyear==$yyear){
        		if($xmonth==$ymonth){
        			$nday=$ydate+1-$xdate;
        		} else {
        			$r2=NULL;
        			$nmonth = $ymonth-$xmonth;            
        			$r1 = $this->nmonth($xmonth)-$xdate+1;
        			for($i=$xmonth+1;$i<$ymonth;$i++){
        				$r2 = $r2+$this->nmonth($i);
        			}
        			$r3 = $ydate;
        			$nday = $r1+$r2+$r3;
        		}
        	} else {
                // Last Year
                //get_nDay
        		$r2=NULL; $r3=NULL;
        		$r1=$this->nmonth($xmonth)-$xdate+1;
                //get_nMonth
        		for($i=$xmonth+1;$i<13;$i++){
        			$r2 = $r2+$this->nmonth($i);
        		}
                // Current Year
        		for($i=1;$i<$ymonth;$i++){
        			$r3 = $r3+$this->nmonth($i);
        		}
        		$r4 = $ydate;
        		$nday = $r1+$r2+$r3+$r4;
        	}            
        	return $nday." Hari";
        }

protected/controllers/LowonganController.php
<?php

class LowonganController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			// 'postOnly + delete', // we only allow deletion via POST request
			);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',
				'actions'=>array('index','view','detail','terbaru','search','data'),
				'users'=>array('*'),
				),
			array('allow',
				'actions'=>array('create','update','view','delete','admin','index','view','terbaru','list','listreport'),
				'users'=>array('@'),
				'expression'=>'Yii::app()->user->getLevel()==1',
				),
			array('allow',
				'actions'=>array('add','update','view','delete','perusahaan','index','view','terbaru','list'),
				'users'=>array('@'),
				'expression'=>'Yii::app()->user->getLevel()==3',
				),			
			array('deny',
				'users'=>array('*'),
				),
			);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$model=$this->loadModel($id);
		$dataNilai=new CActiveDataProvider('PenilaianSaw',
			array('criteria'=>
				array(
					'condition'=>'status=0 AND 
					lowongan_id='.$model->id_lowongan.'',
					'order'=>'nilai DESC')
				)
			);

		$dataUnverify=new FileLamaran('search');
		$dataUnverify->unsetAttributes();  // clear any default values
		if(isset($_GET['FileLamaran']))
			$dataUnverify->attributes=$_GET['FileLamaran'];

		$this->render('view',array(
			'model'=>$this->loadModel($id),
			'dataUnverify'=>$dataUnverify,
			'dataNilai'=>$dataNilai,
			));
	}


	public function actionDetail($id)
	{
		$this->render('detail',array(
			'model'=>$this->loadModel($id),
			));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Lowongan;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Lowongan']))
		{
			$model->attributes=$_POST['Lowongan'];
			$model->tanggal = date('Y-m-d h:m:s');
			$model->user_id = YII::app()->user->id;
			if($model->save())
				$this->redirect(array('view','id'=>$model->id_lowongan));
		}

		$this->render('create',array(
			'model'=>$model,
			));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Lowongan']))
		{
			$model->attributes=$_POST['Lowongan'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id_lowongan));
		}

		$this->render('update',array(
			'model'=>$model,
			));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$this->layout="list";
		$dataProvider=new CActiveDataProvider('Lowongan',array('criteria'=>array('order'=>'id_lowongan DESC')));
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
			));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Lowongan('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Lowongan']))
			$model->attributes=$_GET['Lowongan'];

		$this->render('admin',array(
			'model'=>$model,
			));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Lowongan the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Lowongan::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	public function loadPerusahaan($id)
	{
		$model=Perusahaan::model()->findByAttributes(array('user_id'=>$id));
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}	

	/**
	 * Performs the AJAX validation.
	 * @param Lowongan $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='lowongan-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}

	public function actionTerbaru()
	{
		$this->layout="list";
		$dataProvider=new CActiveDataProvider('Lowongan',array('criteria'=>array('order'=>'id_lowongan DESC')));
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
			));
	}	

	public function actionList()
	{
		$this->layout="admin";
		$dataProvider=new CActiveDataProvider('Lowongan',array('criteria'=>array('order'=>'id_lowongan DESC')));
		$this->render('list',array(
			'dataProvider'=>$dataProvider,
			));
	}


	public function actionListReport()
	{
		$this->layout="admin";
		$dataProvider=new CActiveDataProvider('Lowongan',array('criteria'=>array('order'=>'id_lowongan DESC')));
		$this->render('list_report',array(
			'dataProvider'=>$dataProvider,
			));
	}	

	public function actionSearch($string=''){
		$criteria = new CDbCriteria();
		if(strlen($string)>0)
			$criteria->addSearchCondition('id_lowongan', $string, true, 'OR');
		$dataProvider = new CActiveDataProvider('Lowongan', array('criteria'=>$criteria));
		$this->render('list', array('dataProvider'=>$dataProvider));		
	}	

	public function actionAdd()
	{
		$model=new Lowongan;
		$load=$this->loadPerusahaan(YII::app()->user->id);
		// Uncomment the following line if AJAX validation is needed
		$this->performAjaxValidation($model);

		if(isset($_POST['Lowongan']))
		{
			$model->attributes=$_POST['Lowongan'];
			$model->tanggal = date('Y-m-d h:m:s');
			$model->user_id = YII::app()->user->id;
			$model->perusahaan_id = $load->id_perusahaan;
			if($model->save()){
				$this->redirect(array('view','id'=>$model->id_lowongan));
			}
		}

		$this->render('add',array(
			'model'=>$model,
			));
	}

	public function actionPerusahaan()
	{
		$model=new Lowongan('searchCompany');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Lowongan']))
			$model->attributes=$_GET['Lowongan'];

		$this->render('admin_perusahaan',array(
			'model'=>$model,
			));
	}

	public function actionData()
	{
		$data=Jabatan::model()->findAll('bagian_id=:bagian_id', 
			array(':bagian_id'=>(int) $_POST['bagian_id']));
		$data=CHtml::listData($data,'id_jabatan','nama');
		echo "<option value=''>-- Pilih Jabatan --</option>";
		foreach($data as $value=>$nama)
			echo CHtml::tag('option', array('value'=>$value),CHtml::encode($nama),true);
	}	

}

protected/views/lowongan/_detail_lowongan.php
	<?php 
	$lewat = CHtml::encode(Lowongan::model()->deadline($model->tanggal_kebutuhan));
	if($lewat!="Telah lewat"){

	//Notifikasi Apabila Levelnya tidak Sama dengan = 1 (Admin)
		if(Yii::app()->user->getLevel()!=1):

			if(!YII::app()->user->isGuest){

				$profile=Pelamar::model()->findByAttributes(array('id_user'=>YII::app()->user->id));

				if($profile->jenis_kelamin==$model->jeniskelamin){

					$umur = Pelamar::model()->countBirth($profile->tanggal_lahir);

					if($model->umur>=$umur){
						echo "<br>";

					//Apabila Pelamar sedang dalam Proses Melamar
						if($model->status==1){
							echo Lowongan::model()->cekLamaran($profile->lowongan_id,$model->id_lowongan,YII::app()->user->id);
						}else{
							echo Lowongan::model()->notifikasiLamaran(1);
						}

					}else{

						echo "<div class='alert alert-warning'>Maaf, Maksimal umur lowongan ini ".$model->umur." Tahun - ( Umur Anda Sekarang ".$umur." Tahun )</div>";

					}

				}else{

					echo "<div class='alert alert-warning'>Lowongan Ini Diprioritaskan untuk ".Lowongan::model()->gender($model->jeniskelamin)."</div>";

					if($model->jeniskelamin=="LP"):
						
						if($model->status==1){
							echo Lowongan::model()->cekLamaran($profile->lowongan_id,$model->id_lowongan,YII::app()->user->id);
						}else{
							echo Lowongan::model()->notifikasiLamaran(1);
						}

						endif;

					}

				}else{

			// Cek: Status Lamaran
					if($model->status==1){
				//Notif: Lowongan Masih di Buka
						echo Lowongan::model()->notifikasiLamaran(3);
					}else{
				//Notif: Maaf, Lowongan Ini Sudah Ditutup.
						echo Lowongan::model()->notifikasiLamaran(1);
					}

				}
				endif;


				$this->widget('zii.widgets.CDetailView', array(
					'data'=>$model,
					'htmlOptions'=>array("class"=>"table"),
					'attributes'=>array(
						'tanggal',
						array(
							'name'=>'jabatan',
							'value'=>$model->Jabatan->nama,
							),

						array(
							'name'=>'bagian',
							'value'=>$model->Bagian->nama,
							),

						array(
							'name'=>'umur',
							'value'=>$model->umur,													
							),

						array(
							'name'=>'jeniskelamin',
							'value'=>Lowongan::model()->gender($model->jeniskelamin),													
							),					

						array(
							'name'=>'tipe',
							'value'=>Lowongan::model()->tipe($model->tipe),
							),

						array(
							'name'=>'status',
							'value'=>Lowongan::model()->status($model->status),
							),		

						array(
							'name'=>'jumlah_orang',
							'value'=>$model->jumlah_orang,
							),

						array(
							'name'=>'deskripsi_pekerjaan',
							'value'=>$model->deskripsi_pekerjaan,
							),

						array(
							'name'=>'deskripsi_kebutuhan',
							'value'=>$model->deskripsi_kebutuhan,
							),

						array(
							'name'=>'lokasi',
							'value'=>$model->lokasi,													
							),				

						array(
							'name'=>'jenjang',
							'value'=>Lowongan::model()->educationLevel($model->jenjang),													
							),	
						'nilai',				

						))); 
				


			}else{

				if(YII::app()->user->isGuest):

			//Notif: Maaf, Lowongan Ini Sudah Tidak Tersedia
					echo Lowongan::model()->notifikasiLamaran(2);

				endif;

				if(YII::app()->user->getLevel()==2):

			//Notif: Maaf, Lowongan Ini Sudah Tidak Tersedia
					echo Lowongan::model()->notifikasiLamaran(2);

				endif;
			}

			?>


			<STYLE>
				th{width:100px;}
			</STYLE>

protected/views/lowongan/_detail_lowongan_admin.php
	<?php 


	$this->widget('zii.widgets.CDetailView', array(
		'data'=>$model,
		'htmlOptions'=>array("class"=>"table"),
		'attributes'=>array(
			'tanggal',

			array(
				'name'=>'jabatan',
				'value'=>$model->Jabatan->nama,
				),

			array(
				'name'=>'bagian',
				'value'=>$model->Bagian->nama,
				),

			array(
				'name'=>'umur',
				'value'=>$model->umur,													
				),

			array(
				'name'=>'jeniskelamin',
				'value'=>Lowongan::model()->gender($model->jeniskelamin),													
				),					

			array(
				'name'=>'tipe',
				'value'=>Lowongan::model()->tipe($model->tipe),
				),

			array(
				'name'=>'status',
				'value'=>Lowongan::model()->status($model->status),
				),		

			array(
				'name'=>'jumlah_orang',
				'value'=>$model->jumlah_orang,
				),

			array(
				'name'=>'deskripsi_pekerjaan',
				'value'=>$model->deskripsi_pekerjaan,
				),

			array(
				'name'=>'deskripsi_kebutuhan',
				'value'=>$model->deskripsi_kebutuhan,
				),

			array(
				'name'=>'lokasi',
				'value'=>$model->lokasi,													
				),	

			array(
				'name'=>'jenjang',
				'value'=>Lowongan::model()->educationLevel($model->jenjang),													
				),	
			'nilai',							

			))); 


			?>



			<STYLE>
				th{width:100px;}
			</STYLE>

protected/views/lowongan/_tab_accept.php
<?php
$countApplicant  = FileLamaran::model()->countApplicant(5,$model->id_lowongan); 
if($countApplicant==0){ ?>

	<div class="alert alert-info">Belum ada Data Baru dengan status (Diterima) yang masuk pada ID Lowongan #<?php echo $model->id_lowongan; ?></div>

	<?php }else{ ?>

		<!-- START: Notifikasi Download Report -->
		<div class="alert alert-primary">
			<center><h2 class="text-white">Laporan Seleksi yang telah Diterima disimpan ke Excel, <b class="label label-warning"><a href="<?php echo YII::app()->baseUrl; ?>/Report - Telah Diterima.xls"/>Download Laporan</a></b></h2></center>
		</div>
		<!-- END: Notifikasi Download Report -->
		<!-- Diterima -->
		<?php $this->widget('zii.widgets.grid.CGridView', array(
			'id'=>'file-5-grid',
			'summaryText'=>'',
			'dataProvider'=>$dataUnverify->findStatus(5,$model->id_lowongan),
			'filter'=>$dataUnverify,
			'itemsCssClass' => 'table-responsive table table-striped table-hover table-vcenter',
			'columns'=>array(

				array(
					'class'=>'CButtonColumn',
					'header'=>'Detail',
					'template'=>'{view}',
					'buttons'=>array(
						'view'=>
						array(
							'url'=>'Yii::app()->createUrl("filelamaran/view", array("id"=>$data->id))',
							'imageUrl'=>YII::app()->baseUrl.'images/detail.png',
							),
						),
					),


				'id',
				'tanggal_upload',
				array('name'=>'pelamar_id','value'=>'$data->Pelamar->nama'),
				array('header'=>'Status','value'=>'FileLamaran::model()->status($data->status_lamaran)'),

				),
			)); ?>

			<?php } ?>

protected/views/lowongan/admin.php
<?php
/* @var $this LowonganController */
/* @var $model Lowongan */

$this->breadcrumbs=array(
	'Lowongan'=>array('index'),
	'Kelola',
	);

$this->pageTitle='Kelola Lowongan';
?>
<?php if(Yii::app()->user->getLevel()==1){ ?>

	<div class="col-md-4">

		<?php echo CHtml::link('Tambah',
			array('create'),
			array('class' => 'btn btn-danger btn-flat'));
		?>
		<?php echo CHtml::link('Daftar',
			array('list'),
			array('class' => 'btn btn-danger btn-flat'));
		?>
	</div>

	<div class="col-md-8">
		<?php 
		echo CHtml::beginForm(CHtml::normalizeUrl(array('lowongan/search')), 'get')
		. CHtml::textField('string', (isset($_GET['string'])) ? $_GET['string'] : '', array('id'=>'string','class'=>'form-control input-lg','placeholder'=>'Cari Berdasarkan ID Job Order'))
		. CHtml::endForm();
		?>
	</div>

	<?php }else{ ?>

		<?php echo CHtml::link('Tambah',
			array('add'),
			array('class' => 'btn btn-danger btn-flat'));
		?>
		
		<?php } ?>


		<HR>
			
			<?php $this->widget('zii.widgets.grid.CGridView', array(
				'id'=>'lowongan-grid',
				'dataProvider'=>$model->search(),
			// 'filter'=>$model,
				'itemsCssClass' => 'table table-bordered table-striped dataTable table-hover',
				'columns'=>array(

					array(
						'header'=>'No',
						'value'=>'$this->grid->dataProvider->pagination->currentPage*$this->grid->dataProvider->pagination->pageSize + $row+1',
						'htmlOptions'=>array('width'=>'10px', 
							'style' => 'text-align: center;')),

				// 'tanggal',

					array(
						'name'=>'perusahaan_id',
						'value'=>'Lowongan::model()->perusahaan($data->perusahaan_id)',
						),

					'lokasi',

					'tanggal_kebutuhan',

					array(
						'name'=>'jabatan',
						'value'=>'$data->Jabatan->nama',
						),

					array(
						'name'=>'bagian',
						'value'=>'$data->Bagian->nama',
						),

					array(
						'name'=>'tipe',
						'value'=>'Lowongan::model()->tipe($data->tipe)',
						),

					'jumlah_orang',

				// array(
				// 	'name'=>'status',
				// 	'value'=>'Lowongan::model()->status($data->status)',
				// 	),					

					array(
						'header'=>'Total Pelamar',
						'value'=>'Lowongan::model()->countApply($data->id_lowongan)',
						),		



					array(
						'class'=>'CButtonColumn',
						'header'=>'Detail',
						'template'=>'{view}{update}',
						'buttons'=>array(
							'view'=>
							array(
								'url'=>'Yii::app()->createUrl("lowongan/view", array("id"=>$data->id_lowongan))',
							// 'imageUrl'=>YII::app()->baseUrl.'images/detail.png',
								),
							),
						),
					
					
					),
					)); ?>

protected/views/lowongan/create.php
<?php
/* @var $this LowonganController */
/* @var $model Lowongan */

$this->breadcrumbs=array(
	'Lowongans'=>array('index'),
	'Tambah',
	);

	$this->pageTitle='Tambah Lowongan';
	?>

	<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>